version: '2'
services:
  backend:
      build: .
      depends_on:
        - cassandra
      environment:
        - NODE_ENV=production
        - PORT=8000
      ports:
        - "8000:8000"
      links: 
        - cassandra
      networks: 
        - service
      command: node dist/server.js
  cassandra:
      image: cassandra
      ports:
        - "9042:9042"
      networks:
        - service
      restart: always
networks:
  service:
    driver: "bridge"
