CREATE TABLE containers (
  id INT,
  name VARCHAR,
  PRIMARY KEY (id)
);

CREATE TABLE history_by_container (
  date date,
  temperature INT,
  container_id int,
  PRIMARY KEY ((container_id), date, temperature)
) WITH CLUSTERING ORDER BY (date desc, temperature DESC);

-- RECUERDA QUE CASSANDRA USA CQL EN VEZ DE SQL
-- ESO IMPLICA QUE NO EXISTE LAS RELACIONES ENTRE TABLAS, ESTO HACE QUE NO EXISTAN LOS JOINS
-- LAS CLAVE PRIMARIAS PUEDEN CLUSTERING COLUMNAS CON LA SIGUIENTE SINTAXIS (ESTO SE DEFINE EN LA PK)
-- EJEMPLO PRIMARY KEY ((container_id), date, temperature), FIJATE QUE CONTAINER_ID ESTA DENTRO PARENTESIS
-- EXTRA A LAS DEMAS COLUMNAS, ESO SIGNIFICA QUE CONTAINER_ID ESTA CLUSTERISADA Y ESO PERTMITE FILTRAR EN 
-- LAS CONSULTAS CON UN WHERE, SI LA COLUMNA NO ESTA CLUSTERIZADA NO SE PUEDE INCLUIR EN EL WHERE