BEGIN BATCH
insert into movies_by_genre (genre, year, title) values ('Drama', 2001, '8 Seconds');
insert into movies_by_genre (genre, year, title) values ('Drama', 2000, 'I Am Taraneh, I Am Fifteen Years Old (Man, taraneh, panzdah sal daram)');
insert into movies_by_genre (genre, year, title) values ('Drama', 2000, 'Modern Boy (Modeon boi)');
insert into movies_by_genre (genre, year, title) values ('Drama|Sci-Fi', 2009, 'Killings at Outpost Zeta, The');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1995, 'Into the Arms of Strangers: Stories of the Kindertransport');
insert into movies_by_genre (genre, year, title) values ('Drama', 2010, 'White Mane (Crin blanc: Le cheval sauvage)');
insert into movies_by_genre (genre, year, title) values ('Drama', 1996, 'Poppy Shakespeare');
insert into movies_by_genre (genre, year, title) values ('Adventure|Drama|Fantasy', 1992, 'Fall, The');
insert into movies_by_genre (genre, year, title) values ('Action|Drama|Thriller', 1957, 'Logan''s War: Bound by Honor');
insert into movies_by_genre (genre, year, title) values ('Comedy|Musical', 1995, 'Adventures of Power');
insert into movies_by_genre (genre, year, title) values ('Drama', 1985, 'In This Our Life');
insert into movies_by_genre (genre, year, title) values ('Crime|Horror', 2006, 'Psycho');
insert into movies_by_genre (genre, year, title) values ('Drama|Fantasy', 2005, 'City of Pirates (La ville des pirates) ');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 2006, 'Ay, Carmela! (¡Ay, Carmela!)');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2007, 'Suicide Killers');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Fantasy|Romance', 1984, 'Stranger than Fiction');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 1990, 'Heart of Me, The');
insert into movies_by_genre (genre, year, title) values ('Drama', 1999, 'Dust of Time, The');
insert into movies_by_genre (genre, year, title) values ('Horror|Mystery|Thriller', 2011, 'Retribution (Sakebi)');
insert into movies_by_genre (genre, year, title) values ('Drama|Horror|Thriller', 2006, 'Snapshot');
insert into movies_by_genre (genre, year, title) values ('Thriller', 2001, 'Lesson of the Evil (Aku no kyôten)');
insert into movies_by_genre (genre, year, title) values ('Drama', 2002, 'Town Without Pity');
insert into movies_by_genre (genre, year, title) values ('Action|Thriller', 2011, 'The Last Round');
insert into movies_by_genre (genre, year, title) values ('Drama|Horror|Thriller', 1999, '1408');
insert into movies_by_genre (genre, year, title) values ('Fantasy|Mystery|Thriller', 2002, 'Night Listener, The');
insert into movies_by_genre (genre, year, title) values ('Action|Horror|Sci-Fi', 1988, 'Planet Terror');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2005, 'Midnight Madness');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 1995, 'Trial of the Road (Check-up on the Roads) (Checkpoint) (Proverka na dorogakh)');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2004, 'Cocaine Cowboys');
insert into movies_by_genre (genre, year, title) values ('Adventure|Animation|Children|Romance|Sci-Fi', 2004, 'WALL·E');
insert into movies_by_genre (genre, year, title) values ('Comedy|Documentary|Musical', 2012, 'Hava Nagila: The Movie');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2002, 'Accepted');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1995, 'Empire of Dreams: The Story of the ''Star Wars'' Trilogy');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2001, 'Teenage');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2012, 'Bright Lights');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 1984, 'Sundown');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama', 2000, 'Carlito''s Way');
insert into movies_by_genre (genre, year, title) values ('Action|Crime|Drama|Thriller|IMAX', 1986, 'Fast Five (Fast and the Furious 5, The)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1998, 'Lisa Picard is Famous (a.k.a. Famous)');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2007, 'Mon Oncle (My Uncle)');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama', 2002, 'G Men');
insert into movies_by_genre (genre, year, title) values ('Fantasy', 1996, 'Harvey');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2009, 'Sidewalks of London (St. Martin''s Lane)');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2011, 'Arthur');
insert into movies_by_genre (genre, year, title) values ('Drama', 2005, 'Starting Out in the Evening');
insert into movies_by_genre (genre, year, title) values ('Drama|Thriller', 2002, 'Confess');
insert into movies_by_genre (genre, year, title) values ('Drama', 2005, 'Dangerous Minds');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Fantasy|Sci-Fi', 1984, 'Godzilla vs. The Sea Monster (Gojira-Ebira-Mosura: Nankai no daiketto)');
insert into movies_by_genre (genre, year, title) values ('Adventure|Drama', 2011, 'Male and Female');
insert into movies_by_genre (genre, year, title) values ('Drama', 2007, 'Star Maker, The (Uomo delle stelle, L'')');
insert into movies_by_genre (genre, year, title) values ('Drama', 2011, 'Suburbans, The');
insert into movies_by_genre (genre, year, title) values ('Drama', 1994, 'Ghosts (Gespenster)');
insert into movies_by_genre (genre, year, title) values ('Drama', 2009, 'Socialism (Film socialisme)');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Horror|Thriller', 2002, 'Sweeney Todd');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 2007, 'Bigger Than the Sky');
insert into movies_by_genre (genre, year, title) values ('Horror|Sci-Fi', 1985, 'Leech Woman, The');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1992, 'Feet First');
insert into movies_by_genre (genre, year, title) values ('Comedy|Horror', 1994, 'American Zombie');
insert into movies_by_genre (genre, year, title) values ('Crime|Horror|Thriller', 2011, 'Sick Girl');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1999, 'Let''s Do It Again');
insert into movies_by_genre (genre, year, title) values ('Adventure|Animation|Children|Western', 2010, 'Spirit: Stallion of the Cimarron');
insert into movies_by_genre (genre, year, title) values ('Drama', 2006, 'Foolish Wives');
insert into movies_by_genre (genre, year, title) values ('Comedy|Horror', 2011, 'Drag Me to Hell');
insert into movies_by_genre (genre, year, title) values ('Thriller', 2005, 'El Lobo');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Thriller', 2003, 'FBI Story, The');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1994, 'Animal, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 1990, 'Party 2, The (Boum 2, La)');
insert into movies_by_genre (genre, year, title) values ('Mystery|Thriller', 2001, 'Mystery Road');
insert into movies_by_genre (genre, year, title) values ('Drama|Mystery', 2007, 'Apartment 4E ');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama', 2004, 'Auto Focus');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2011, 'Bikini Summer');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 2012, 'Being Julia');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2005, 'You''re Telling Me!');
insert into movies_by_genre (genre, year, title) values ('Action|Crime|Drama', 2001, 'Public Enemy, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 2010, 'Ex, The');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2006, 'One Fine Day');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 1993, 'Last Resort');
insert into movies_by_genre (genre, year, title) values ('Drama|Fantasy', 1999, 'Dance of Reality, The (Danza de la realidad, La)');
insert into movies_by_genre (genre, year, title) values ('Action|Animation|Comedy|Crime|Drama|Mystery|Romance|Thriller', 1990, 'Lupin III: First Contact (Rupan Sansei: Faasuto Kontakuto)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Horror|Mystery|Thriller', 1993, 'Scream');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2007, 'My Mom Is a Character (Minha Mãe é uma Peça: O Filme)');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 1996, 'Must Have Been Love');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Romance', 2007, 'Havoc');
insert into movies_by_genre (genre, year, title) values ('Horror|Sci-Fi|Thriller', 2001, 'Ghostmaker, The (Box of Shadows)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 2006, 'Grave Decisions (Wer früher stirbt, ist länger tot)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Crime', 1997, 'Guard, The');
insert into movies_by_genre (genre, year, title) values ('Action|Children|Comedy|Fantasy', 2007, 'Alone for Christmas');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama', 2011, 'Innocent Man, An');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Drama', 1970, 'Man in the Iron Mask, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Fantasy|Horror|Sci-Fi|Thriller', 2005, 'Puppet Master vs. Demonic Toys (Puppet Master 9)');
insert into movies_by_genre (genre, year, title) values ('Adventure|Drama|Mystery', 2000, 'Final Inquiry, The (Inquiry, The) (inchiesta, L'')');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1989, 'One Chance');
insert into movies_by_genre (genre, year, title) values ('Drama', 1989, 'Land of Happines (Onnen maa)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1997, 'Amy');
insert into movies_by_genre (genre, year, title) values ('Drama|Fantasy|Romance', 1994, 'Charlie St. Cloud');
insert into movies_by_genre (genre, year, title) values ('Adventure|Sci-Fi', 2009, 'Doctor Who');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Sci-Fi', 1996, 'Truman Show, The');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1999, 'Year of the Yao, The');
insert into movies_by_genre (genre, year, title) values ('Animation|Comedy|Drama|Fantasy', 1995, 'Pom Poko (a.k.a. Raccoon War, The) (Heisei tanuki gassen pompoko)');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1992, 'Madhouse');
insert into movies_by_genre (genre, year, title) values ('Comedy|Western', 1988, 'Arrapaho');
insert into movies_by_genre (genre, year, title) values ('Horror|Romance|Thriller', 1990, 'Forget Me Not');
insert into movies_by_genre (genre, year, title) values ('Action|War', 2011, 'Casablanca Express');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Fantasy|Romance|Thriller', 2012, 'Ghost');
insert into movies_by_genre (genre, year, title) values ('Comedy|Crime|Thriller', 2007, 'Mortel transfert');
insert into movies_by_genre (genre, year, title) values ('Horror', 1994, 'Pharaoh''s Curse');
insert into movies_by_genre (genre, year, title) values ('Drama|Mystery', 2002, 'Agnes of God');
insert into movies_by_genre (genre, year, title) values ('Children|Comedy|Musical', 2006, 'Muppet Christmas Carol, The');
insert into movies_by_genre (genre, year, title) values ('Animation|Children|Comedy', 2008, 'Tom and Jerry: The Movie');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2002, 'Princess and the Warrior, The (Krieger und die Kaiserin, Der)');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2010, 'Animal Kingdom, The');
insert into movies_by_genre (genre, year, title) values ('Drama', 1988, 'Vitelloni, I (a.k.a. The Young and the Passionate)');
insert into movies_by_genre (genre, year, title) values ('Western', 1964, 'Blackthorn');
insert into movies_by_genre (genre, year, title) values ('Comedy|Thriller', 2008, 'Cable Guy, The');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Sci-Fi|Thriller', 2008, 'Star Trek II: The Wrath of Khan');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Mystery|Thriller', 2012, 'Doomed to Die');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 1986, 'Daisy');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Fantasy|Sci-Fi', 2012, 'Beastmaster 2: Through the Portal of Time');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2001, 'Vegas Vacation (National Lampoon''s Las Vegas Vacation)');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1993, 'Major Barbara');
insert into movies_by_genre (genre, year, title) values ('Drama|Horror|Thriller', 2000, 'Dark Prince: The True Story of Dracula');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama', 1996, 'Accident');
insert into movies_by_genre (genre, year, title) values ('Adventure|Drama|Thriller', 1985, 'No Turning Back');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Comedy|Drama', 2004, 'Wrecking Crew, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 2012, 'Perfume');
insert into movies_by_genre (genre, year, title) values ('Drama', 2007, 'The Oscar');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 1991, 'Geography Club');
insert into movies_by_genre (genre, year, title) values ('Action|Comedy|Horror|Romance', 1999, 'Vampire Girl vs. Frankenstein Girl (Kyûketsu Shôjo tai Shôjo Furanken)');
insert into movies_by_genre (genre, year, title) values ('Action', 2000, 'Expert, The');
insert into movies_by_genre (genre, year, title) values ('Drama', 2013, 'Restaurant');
insert into movies_by_genre (genre, year, title) values ('Children|Comedy', 1996, 'Shaggy Dog, The');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 1995, 'Six in Paris (Paris vu par...)');
insert into movies_by_genre (genre, year, title) values ('Horror|Mystery', 2011, 'Psychopath, The');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Sci-Fi|Western', 1996, 'Space Raiders');
insert into movies_by_genre (genre, year, title) values ('Horror|Mystery', 1968, 'Willow Creek');
insert into movies_by_genre (genre, year, title) values ('Adventure|Comedy|Crime|Romance', 2004, 'Those Daring Young Men in Their Jaunty Jalopies');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 2008, 'I''m Reed Fish');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 2003, '18 Years Later (Diciotto anni dopo)');
insert into movies_by_genre (genre, year, title) values ('Children|Musical|Sci-Fi', 1990, 'Little Prince, The');
insert into movies_by_genre (genre, year, title) values ('Horror|Sci-Fi', 2007, 'Convent, The');
insert into movies_by_genre (genre, year, title) values ('Action|Crime', 2011, 'Run Lola Run (Lola rennt)');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1991, 'Lightning Bolt: The Power of Salad');
insert into movies_by_genre (genre, year, title) values ('Adventure|Comedy|Drama', 2000, 'Secret Life of Walter Mitty, The');
insert into movies_by_genre (genre, year, title) values ('Drama|Mystery|Thriller', 2002, 'Turks & Caicos');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 1996, 'Peyton Place');
insert into movies_by_genre (genre, year, title) values ('Comedy|Horror', 2009, 'Return of the Living Dead Part II');
insert into movies_by_genre (genre, year, title) values ('Drama', 2009, 'Pandora''s Box (Büchse der Pandora, Die)');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1996, 'Marwencol');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2011, 'Angels and Insects');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1992, 'Held Up');
insert into movies_by_genre (genre, year, title) values ('Documentary|Sci-Fi', 1999, 'Mars');
insert into movies_by_genre (genre, year, title) values ('Drama|Thriller', 1977, 'Everything Will Be Fine');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1988, 'Unknown Woman, The (Tuntematon emäntä)');
insert into movies_by_genre (genre, year, title) values ('Horror', 2006, 'Leprechaun: Origins');
insert into movies_by_genre (genre, year, title) values ('Action|Drama|War', 1991, 'Captains of the Clouds');
insert into movies_by_genre (genre, year, title) values ('Horror', 2011, 'Halloween');
insert into movies_by_genre (genre, year, title) values ('Drama', 2012, 'Al otro lado');
insert into movies_by_genre (genre, year, title) values ('Action', 2006, 'Last Castle, The');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 1999, 'Soft Shell Man (Un crabe dans la tête)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1997, 'Balkan Spy (Balkanski spijun)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance|Sci-Fi', 2007, 'Free Enterprise');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 2007, 'Finding North');
insert into movies_by_genre (genre, year, title) values ('Adventure|Drama|Thriller', 2001, 'Dark Tide');
insert into movies_by_genre (genre, year, title) values ('Drama', 2003, 'Gervaise');
insert into movies_by_genre (genre, year, title) values ('Horror', 1991, 'Zombie Island Massacre');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1993, 'Four Christmases');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|War', 2011, 'Where Eagles Dare');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2007, 'Fat People (Gordos)');
insert into movies_by_genre (genre, year, title) values ('Horror|Thriller', 2007, 'Fear');
insert into movies_by_genre (genre, year, title) values ('Drama', 2005, 'Cantinflas');
insert into movies_by_genre (genre, year, title) values ('Horror', 1999, 'Apartment 1303');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Fantasy|Romance', 2004, 'Big');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 2001, 'Hiding Place, The');
insert into movies_by_genre (genre, year, title) values ('Drama', 2003, 'Blonde Venus');
insert into movies_by_genre (genre, year, title) values ('Action|Drama|Sci-Fi|IMAX', 1995, 'Elysium');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama', 1985, 'Ali Zoua: Prince of the Streets (Ali Zaoua, prince de la rue)');
insert into movies_by_genre (genre, year, title) values ('Drama', 1992, 'Net Worth');
insert into movies_by_genre (genre, year, title) values ('Drama', 1993, 'Facing the Truth (At kende sandheden)');
insert into movies_by_genre (genre, year, title) values ('Drama|Musical|Romance', 1996, 'If You Love (Jos rakastat)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 2009, 'Your Sister''s Sister');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 1998, 'Magnificent Obsession');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Fantasy', 1997, 'Alice');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1995, 'A Night at the Movies: The Suspenseful World of Thrillers');
insert into movies_by_genre (genre, year, title) values ('Drama|Musical|Romance', 2002, 'Aashiqui 2');
insert into movies_by_genre (genre, year, title) values ('Children|Comedy|Drama', 1993, 'Son of Rambow');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama', 2010, 'Young Americans, The');
insert into movies_by_genre (genre, year, title) values ('Action|Drama|Mystery', 2011, 'Naan Kadavul');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 1988, 'Running Mates');
insert into movies_by_genre (genre, year, title) values ('Drama', 2012, 'Jobs');
insert into movies_by_genre (genre, year, title) values ('Adventure|Comedy|Crime', 2013, 'O Brother, Where Art Thou?');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1992, 'Bad Chicken');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 1993, 'Myth of the American Sleepover, The');
insert into movies_by_genre (genre, year, title) values ('Thriller', 2008, 'Dangerous Place, A');
insert into movies_by_genre (genre, year, title) values ('Drama', 2000, 'Story of Ruth, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1993, 'Grace of My Heart');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1972, 'Lumihiutalemuodostelma');
insert into movies_by_genre (genre, year, title) values ('Action', 1993, 'Raw Deal');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 2003, 'Sexual Chronicles of a French Family (Chroniques sexuelles d''une famille d''aujourd''hui)');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Comedy', 2004, 'Friend Is a Treasure, A (Chi Trova Un Amico, Trova un Tesoro) (Who Finds a Friend Finds a Treasure)');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2007, 'Upstairs and Downstairs');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 1992, 'Ascent, The (Voskhozhdeniye)');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Crime|Thriller', 2002, 'Hard Target');
insert into movies_by_genre (genre, year, title) values ('Children|Comedy|Fantasy', 1999, 'Fred Claus');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2008, 'Patience (After Sebald)');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2011, 'American Pastime');
insert into movies_by_genre (genre, year, title) values ('Drama', 1992, 'Long Day''s Journey Into Night');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2004, 'Escanaba in da Moonlight');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama', 2009, 'Unholy Three, The');
insert into movies_by_genre (genre, year, title) values ('Horror|Thriller', 1995, 'Rings');
insert into movies_by_genre (genre, year, title) values ('Drama', 1994, 'Lili Marleen');
insert into movies_by_genre (genre, year, title) values ('Drama', 1975, 'Amorosa');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 2000, 'Night on Earth');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2002, 'New Waterford Girl');
insert into movies_by_genre (genre, year, title) values ('Action|Animation|Comedy|Drama|Fantasy', 2004, 'Lady and the Reaper, The (Dama y la muerte, La)');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Drama', 1998, 'Milarepa');
insert into movies_by_genre (genre, year, title) values ('Action|Drama|Romance|War', 1997, 'Kingdom of Heaven');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Musical|Romance', 1993, 'Destiny (Al-massir)');
insert into movies_by_genre (genre, year, title) values ('Drama', 2009, 'Angel');
insert into movies_by_genre (genre, year, title) values ('Sci-Fi', 1996, 'Taken');
insert into movies_by_genre (genre, year, title) values ('Action|Drama', 2001, 'Rocky V');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2010, 'Page Miss Glory');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 2003, 'Sex and the City');
insert into movies_by_genre (genre, year, title) values ('Drama|Thriller', 2005, 'Gray Lady Down');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2000, 'Pete Smalls Is Dead');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 1979, 'Catered Affair, The');
insert into movies_by_genre (genre, year, title) values ('Mystery|Thriller', 1992, 'Strange Color Of Your Body''s Tears, The (L''étrange couleur des larmes de ton corps)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Fantasy', 2006, 'Ghost Dad');
insert into movies_by_genre (genre, year, title) values ('Drama', 1991, 'Other Woman, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1997, 'Riding in Cars with Boys');
insert into movies_by_genre (genre, year, title) values ('Drama|Fantasy|Mystery|Sci-Fi', 2004, 'K-PAX');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1992, 'Off the Map');
insert into movies_by_genre (genre, year, title) values ('Drama', 2011, 'East of Eden');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 2005, 'Ashes, The (Popioly)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1992, 'Upswing (Nousukausi)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Documentary', 1993, 'Richard Pryor: Live in Concert');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 1986, 'Broadcast News');
insert into movies_by_genre (genre, year, title) values ('Drama|Thriller', 2001, 'Gossip');
insert into movies_by_genre (genre, year, title) values ('Action|Drama|War', 2009, 'Darby''s Rangers');
insert into movies_by_genre (genre, year, title) values ('Drama', 1998, 'Man in the Glass Booth, The');
insert into movies_by_genre (genre, year, title) values ('Animation|Comedy', 1994, 'Seven Brothers (Seitsemän veljestä)');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Comedy|Fantasy', 2008, 'Pirates of the Caribbean: At World''s End');
insert into movies_by_genre (genre, year, title) values ('Comedy|War', 2006, 'Two Men Went to War');
insert into movies_by_genre (genre, year, title) values ('Drama', 2000, 'Girl');
insert into movies_by_genre (genre, year, title) values ('Horror|War|Western', 1986, 'Dead Birds');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2012, 'Trio, The (Trio, Das)');
insert into movies_by_genre (genre, year, title) values ('Romance|Thriller', 1993, 'Attack, The');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Thriller', 1995, 'Deadfall');
insert into movies_by_genre (genre, year, title) values ('Action|Crime|Sci-Fi|Thriller', 2012, 'RoboCop 2');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Comedy|Thriller', 1994, 'First Strike (Police Story 4: First Strike) (Ging chaat goo si 4: Ji gaan daan yam mo)');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1992, 'Sexo, Amor e Traição');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 2005, 'Grass Is Greener, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Crime|Drama|Romance', 1998, 'Edukators, The (Die Fetten Jahre sind vorbei)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 1990, 'Norbit');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2010, 'In a World...');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2007, 'Millie');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2002, 'Human Traffic');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2011, 'Winning Season, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Sci-Fi', 2010, 'Short Circuit 2');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1998, 'Wildcats');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 2001, 'Caine Mutiny Court-Martial, The');
insert into movies_by_genre (genre, year, title) values ('Adventure|Animation|Children', 2013, 'Dinosaur');
insert into movies_by_genre (genre, year, title) values ('Action|Drama', 2005, 'Red Line 7000');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2012, 'L''antisémite');
insert into movies_by_genre (genre, year, title) values ('Crime|Horror|Mystery|Thriller', 1984, 'Slaughter of the Innocents');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2009, 'Numbskull Emptybrook in the Army (Uuno Turhapuro armeijan leivissä)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 2009, 'Public Sex');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 2011, 'Before the Rain (Pred dozhdot)');
insert into movies_by_genre (genre, year, title) values ('Adventure|Fantasy|Mystery|Thriller', 2000, 'Viy');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2007, 'Beyond the Rocks');
insert into movies_by_genre (genre, year, title) values ('Drama|Thriller', 2009, 'Pandora''s Box');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2009, 'Crisis: Behind a Presidential Commitment');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1994, 'Bamboozled');
insert into movies_by_genre (genre, year, title) values ('Horror|Sci-Fi|Thriller', 1993, 'Village of the Damned');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Thriller', 2004, 'Texas Killing Fields');
insert into movies_by_genre (genre, year, title) values ('Horror|Thriller', 2000, 'Broken');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 2007, 'Look Who''s Talking');
insert into movies_by_genre (genre, year, title) values ('Crime|Thriller', 1999, 'Dead in the Water');
insert into movies_by_genre (genre, year, title) values ('Crime|Thriller|Western', 2010, 'Red Hill');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 1993, '55 Days at Peking');
insert into movies_by_genre (genre, year, title) values ('Adventure|Comedy|Fantasy', 1992, 'Adventures of Baron Munchausen, The');
insert into movies_by_genre (genre, year, title) values ('Adventure|Comedy|Sci-Fi', 2001, 'Man with the Screaming Brain');
insert into movies_by_genre (genre, year, title) values ('Comedy|Sci-Fi', 2008, 'Tammy and the T-Rex');
insert into movies_by_genre (genre, year, title) values ('Documentary|Drama|War', 2002, 'Culloden (The Battle of Culloden)');
insert into movies_by_genre (genre, year, title) values ('Drama|Horror|Thriller', 1986, 'Hurt');
insert into movies_by_genre (genre, year, title) values ('Horror', 1986, 'Ju-on: The Grudge');
insert into movies_by_genre (genre, year, title) values ('Animation|Sci-Fi', 2009, 'Metropia');
insert into movies_by_genre (genre, year, title) values ('Drama', 2008, 'Kira''s Reason: A Love Story (En Kærlighedshistorie)');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2006, 'Must Have Been Love');
insert into movies_by_genre (genre, year, title) values ('Comedy|Horror|Musical', 2003, 'Dead & Breakfast');
insert into movies_by_genre (genre, year, title) values ('Drama', 1999, 'Teacher, A');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1998, 'SubUrbia');
insert into movies_by_genre (genre, year, title) values ('Drama', 1969, 'Drevo');
insert into movies_by_genre (genre, year, title) values ('Action|Comedy|Crime|Drama', 2001, 'Cab for Three, A (Taxi para tres)');
insert into movies_by_genre (genre, year, title) values ('Horror', 1993, 'Pet Sematary');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1972, 'Capricious Summer (Rozmarné léto)');
insert into movies_by_genre (genre, year, title) values ('Action|Drama', 1994, 'Series 7: The Contenders');
insert into movies_by_genre (genre, year, title) values ('Thriller', 1988, 'Heatstroke');
insert into movies_by_genre (genre, year, title) values ('Drama', 1986, 'Sayonara');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 2002, 'Avenue Montaigne (Fauteuils d''orchestre)');
insert into movies_by_genre (genre, year, title) values ('Drama', 2005, 'Dreamlife of Angels, The (Vie rêvée des anges, La)');
insert into movies_by_genre (genre, year, title) values ('Drama', 2009, 'Katze im Sack');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2008, 'Short Game, The');
insert into movies_by_genre (genre, year, title) values ('Drama', 2005, 'Other Girls');
insert into movies_by_genre (genre, year, title) values ('Documentary|Drama', 2007, 'Khodorkovsky');
insert into movies_by_genre (genre, year, title) values ('Action|Drama|Thriller', 2004, 'Mechanic, The');
insert into movies_by_genre (genre, year, title) values ('Drama', 2007, 'On the Occasion of Remembering the Turning Gate (Saenghwalui balgyeon)');
insert into movies_by_genre (genre, year, title) values ('Horror|Sci-Fi', 1999, 'Shadowzone');
insert into movies_by_genre (genre, year, title) values ('Western', 2008, 'The Five Man Army');
insert into movies_by_genre (genre, year, title) values ('Documentary|Musical', 1997, 'Don''t Look Back');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 2005, 'Round Up, The (La Rafle)');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1996, 'Encounters at the End of the World');
insert into movies_by_genre (genre, year, title) values ('Drama', 1993, 'Boris Godunov');
insert into movies_by_genre (genre, year, title) values ('Drama', 2005, 'Opfergang');
insert into movies_by_genre (genre, year, title) values ('Animation|Children|Comedy', 2011, 'Kung Fu Panda Holiday Special');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Film-Noir|Thriller', 1989, 'Postman Always Rings Twice, The');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 2000, 'So Ends Our Night');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2003, 'Gonzo: The Life and Work of Dr. Hunter S. Thompson');
insert into movies_by_genre (genre, year, title) values ('Drama', 2008, 'Soft Skin, The (La peau douce)');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1998, 'Summer School');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Drama', 1975, 'South Shaolin Master, The (Nan quan wang)');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Drama|Romance|War', 2001, 'River Queen');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance|War', 2001, 'Children of Glory (Szabadság, szerelem)');
insert into movies_by_genre (genre, year, title) values ('Crime|Romance', 2012, 'You and Me');
insert into movies_by_genre (genre, year, title) values ('Crime|Mystery|Thriller', 2011, 'The Trap');
insert into movies_by_genre (genre, year, title) values ('Horror|Thriller', 1992, 'Kill Theory');
insert into movies_by_genre (genre, year, title) values ('Adventure', 1958, 'Against The Sun');
insert into movies_by_genre (genre, year, title) values ('Action|War', 2009, 'Too Late the Hero');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 2009, 'Lover Come Back');
insert into movies_by_genre (genre, year, title) values ('Animation|Children', 2008, 'Bugs Bunny''s Looney Christmas Tales');
insert into movies_by_genre (genre, year, title) values ('Action|Drama|Sci-Fi|Thriller', 2011, 'Star Trek: Nemesis');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 2012, 'Housefull 2');
insert into movies_by_genre (genre, year, title) values ('Drama|Film-Noir|Mystery|Thriller', 1998, 'House on Telegraph Hill, The');
insert into movies_by_genre (genre, year, title) values ('Drama', 2009, 'Deal, The');
insert into movies_by_genre (genre, year, title) values ('Action|Sci-Fi|Thriller', 1995, 'Total Recall');
insert into movies_by_genre (genre, year, title) values ('Western', 1997, 'The Dark Valley');
insert into movies_by_genre (genre, year, title) values ('Drama', 1954, 'Permanent Midnight');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 2002, 'Self-Made Hero, A (Un héros très discret)');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama', 2009, 'Mickey One');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Animation|Children', 2009, 'Dragon Ball: The Curse Of The Blood Rubies (Doragon bôru: Shenron no densetsu)');
insert into movies_by_genre (genre, year, title) values ('Drama|Mystery', 1993, 'Skin');
insert into movies_by_genre (genre, year, title) values ('Drama|Mystery|Thriller', 2011, 'Fallen Idol, The');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1998, 'Salesman');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2009, 'Remember Me');
insert into movies_by_genre (genre, year, title) values ('Adventure|Comedy|Fantasy', 2012, 'Son of Kong, The');
insert into movies_by_genre (genre, year, title) values ('Drama|Western', 2004, 'Shootist, The');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 1996, 'Beware of Pity');
insert into movies_by_genre (genre, year, title) values ('Drama', 2007, 'Rich and Famous');
insert into movies_by_genre (genre, year, title) values ('Action|Drama|Thriller', 1993, 'Professional, The (Le professionnel)');
insert into movies_by_genre (genre, year, title) values ('Action|Fantasy', 2011, 'BloodRayne');
insert into movies_by_genre (genre, year, title) values ('Drama', 2006, 'Aningaaq');
insert into movies_by_genre (genre, year, title) values ('Drama', 2004, 'Cruel Intentions');
insert into movies_by_genre (genre, year, title) values ('Drama|Musical', 2010, 'Evita');
insert into movies_by_genre (genre, year, title) values ('Horror|Thriller', 1990, 'Corridor, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1989, 'Better Living Through Chemistry');
insert into movies_by_genre (genre, year, title) values ('Action|Crime|Drama|Thriller', 2006, 'Taken 2');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 1996, 'Thick-Walled Room, The (Kabe atsuki heya)');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2001, 'Elvis and Anabelle');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 2011, 'Bongwater');
insert into movies_by_genre (genre, year, title) values ('Crime|Documentary', 1993, 'After Innocence');
insert into movies_by_genre (genre, year, title) values ('Comedy|Crime|Romance', 2012, 'Grosse Pointe Blank');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2010, 'Who Is Harry Nilsson (And Why Is Everybody Talkin'' About Him?)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 2013, 'Getting It Right');
insert into movies_by_genre (genre, year, title) values ('Action|Drama', 2004, 'New Fist of Fury (Xin jing wu men)');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2012, 'Made in Jamaica');
insert into movies_by_genre (genre, year, title) values ('Comedy|Crime', 1993, 'The Red Inn');
insert into movies_by_genre (genre, year, title) values ('Comedy|Crime', 2002, 'Whole Town''s Talking, The (Passport to Fame)');
insert into movies_by_genre (genre, year, title) values ('Adventure|Drama', 2009, 'Edge, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Crime|Mystery', 1993, 'Scarlet Clue, The (Charlie Chan in the Scarlet Clue)');
insert into movies_by_genre (genre, year, title) values ('Drama', 2004, 'Starlet');
insert into movies_by_genre (genre, year, title) values ('Action|Crime|Drama|Thriller', 2008, 'Pressed');
insert into movies_by_genre (genre, year, title) values ('Children|Drama', 1997, 'Seven Alone');
insert into movies_by_genre (genre, year, title) values ('Action|Crime|Drama|Thriller', 2010, 'Boondock Saints II: All Saints Day, The');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Thriller', 2006, 'Interrogation (Przesluchanie)');
insert into movies_by_genre (genre, year, title) values ('Action|Sci-Fi', 1998, 'Aeon Flux');
insert into movies_by_genre (genre, year, title) values ('Action|Sci-Fi|Thriller', 2006, 'X-Men Origins: Wolverine');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 2011, 'Coffee and Cigarettes');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Musical|Romance', 1994, 'Under the Cherry Moon');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama', 2011, 'Oliver Twist');
insert into movies_by_genre (genre, year, title) values ('Drama', 1986, 'Downstairs');
insert into movies_by_genre (genre, year, title) values ('Horror|Thriller', 1994, 'After...');
insert into movies_by_genre (genre, year, title) values ('Animation|Fantasy', 1996, 'Fire and Ice');
insert into movies_by_genre (genre, year, title) values ('Adventure', 1992, 'To Be King (Koning van Katoren)');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2008, 'Life and Times of Hank Greenberg, The');
insert into movies_by_genre (genre, year, title) values ('Drama', 1993, 'Low Down, The');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1996, 'Wrestling for Jesus: The Tale of T-Money');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Mystery', 2008, 'Zen Noir');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1984, 'Cabin Boy');
insert into movies_by_genre (genre, year, title) values ('Action|Comedy', 1990, 'Brain Smasher... A Love Story (Bouncer and the Lady, The)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 1997, 'Battle in Heaven (Batalla en el cielo)');
insert into movies_by_genre (genre, year, title) values ('Drama', 1985, 'Laws of Gravity');
insert into movies_by_genre (genre, year, title) values ('(no genres listed)', 2011, 'The Iron Commissioner');
insert into movies_by_genre (genre, year, title) values ('Drama', 1987, '2 ou 3 choses que je sais d''elle (2 or 3 Things I Know About Her)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1989, 'Lumihiutalemuodostelma');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2006, 'Head-On (Gegen die Wand)');
insert into movies_by_genre (genre, year, title) values ('Drama|Horror|Thriller', 2012, 'Carrie');
insert into movies_by_genre (genre, year, title) values ('Drama', 2003, 'I Am Michael');
insert into movies_by_genre (genre, year, title) values ('Drama|Film-Noir', 1999, 'Letter, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Fantasy|Sci-Fi', 1988, 'Nothing Lasts Forever ');
insert into movies_by_genre (genre, year, title) values ('Drama|Thriller', 1989, 'Map of the Sounds of Tokyo');
insert into movies_by_genre (genre, year, title) values ('Drama', 2002, 'Song of the Little Road (Pather Panchali)');
insert into movies_by_genre (genre, year, title) values ('Drama', 1995, 'Main Street');
insert into movies_by_genre (genre, year, title) values ('Drama', 2012, 'Legendary');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1985, 'Fuse (Gori vatra)');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Horror|Thriller', 1995, 'L: Change the World');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 2003, 'Drei Stunden');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 2006, 'Last of Mrs. Cheyney, The');
insert into movies_by_genre (genre, year, title) values ('Action|Horror|Sci-Fi|War', 2004, 'Starship Troopers 2: Hero of the Federation');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2009, 'Beautiful Person, The (La belle personne)');
insert into movies_by_genre (genre, year, title) values ('Crime|Horror|Thriller', 2000, 'Black Room, The');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama', 1996, 'Rhythm of a Crime (Ritam zlocina)');
insert into movies_by_genre (genre, year, title) values ('Action', 2009, 'Red Scorpion');
insert into movies_by_genre (genre, year, title) values ('Drama', 1998, 'Lumumba');
insert into movies_by_genre (genre, year, title) values ('Comedy|Horror|Thriller', 2001, 'Child''s Play 3');
insert into movies_by_genre (genre, year, title) values ('Drama', 1988, 'Fool for Love');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 1993, 'Wife vs. Secretary');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2002, 'Beach Party');
insert into movies_by_genre (genre, year, title) values ('Drama|Mystery', 2008, 'Les disparus de Saint-Agil');
insert into movies_by_genre (genre, year, title) values ('Drama|Horror|Sci-Fi', 1991, 'Dorian Gray');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2004, 'Let''s Do It Again');
insert into movies_by_genre (genre, year, title) values ('Drama', 2008, 'Fetching Cody');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2011, 'Edie & Pen');
insert into movies_by_genre (genre, year, title) values ('Documentary|Drama|Sci-Fi', 2002, 'Fata Morgana');
insert into movies_by_genre (genre, year, title) values ('Drama', 1988, 'Roadracers');
insert into movies_by_genre (genre, year, title) values ('Drama|Fantasy', 2008, 'After Life (Wandafuru raifu)');
insert into movies_by_genre (genre, year, title) values ('Drama', 1987, 'Hamlet, Prince of Denmark');
insert into movies_by_genre (genre, year, title) values ('Animation', 2009, 'Mail Early for Xmas');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2002, 'The Do-Deca-Pentathlon');
insert into movies_by_genre (genre, year, title) values ('Drama|Mystery', 2010, 'Charlie Chan in London');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Crime|Thriller', 2008, 'Live Free or Die Hard');
insert into movies_by_genre (genre, year, title) values ('Drama', 2009, 'Tennessee Johnson');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1994, 'Calamari Union');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Crime|Western', 2007, 'Gun Fury');
insert into movies_by_genre (genre, year, title) values ('Drama', 1992, 'Mark of Cain, The');
insert into movies_by_genre (genre, year, title) values ('Action|Thriller', 2006, 'Art of War, The');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Fantasy|Mystery|Sci-Fi', 2008, 'Adventures of Captain Marvel');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1998, 'Kiss and Tell');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1995, 'Half Baked');
insert into movies_by_genre (genre, year, title) values ('Action|Horror|Sci-Fi', 2011, '28 Days Later');
insert into movies_by_genre (genre, year, title) values ('Drama', 1992, 'Along the Sungari River (Song hua jiang shang)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Musical|Romance', 2012, 'Pajama Game, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Documentary', 1994, 'Kumail Nanjiani: Beta Male ');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2007, 'Sliding Doors');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2009, 'Pest, The');
insert into movies_by_genre (genre, year, title) values ('Drama|Mystery|Thriller', 2000, 'Lemming');
insert into movies_by_genre (genre, year, title) values ('Adventure|Children|Musical', 1998, 'Bedknobs and Broomsticks');
insert into movies_by_genre (genre, year, title) values ('Horror', 1996, 'Cannibal Holocaust');
insert into movies_by_genre (genre, year, title) values ('Action|War', 2007, 'Heartbreak Ridge');
insert into movies_by_genre (genre, year, title) values ('Drama', 2007, 'Intruder, The (L''intrus)');
insert into movies_by_genre (genre, year, title) values ('Thriller', 1995, 'New World (Shin-sae-gye)');
insert into movies_by_genre (genre, year, title) values ('Adventure|Children|Comedy|Drama', 1996, 'For the Love of Benji');
insert into movies_by_genre (genre, year, title) values ('Children|Comedy', 1994, 'Little Giants');
insert into movies_by_genre (genre, year, title) values ('Fantasy|Horror', 2003, 'Shanks');
insert into movies_by_genre (genre, year, title) values ('Drama', 2007, 'Broderskab (Brotherhood)');
insert into movies_by_genre (genre, year, title) values ('Mystery', 1998, 'Bishop Murder Case, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Sci-Fi', 1984, 'Short Circuit');
insert into movies_by_genre (genre, year, title) values ('Drama', 2008, 'Americano');
insert into movies_by_genre (genre, year, title) values ('Action|Western', 2003, 'Crossfire Trail (Louis L''Amour''s ''Crossfire Trail'')');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1989, 'Winter Nomads');
insert into movies_by_genre (genre, year, title) values ('Drama', 2006, 'Standing Aside, Watching');
insert into movies_by_genre (genre, year, title) values ('Animation|Children|Drama|Musical|Romance', 2011, 'Hunchback of Notre Dame, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Musical|Romance', 2000, 'Transistor Love Story (Monrak Transistor)');
insert into movies_by_genre (genre, year, title) values ('Horror|Thriller', 2001, 'Razorback');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2011, 'Small Town Gay Bar');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 1985, 'Country Life');
insert into movies_by_genre (genre, year, title) values ('Crime', 2013, 'Chained for Life');
insert into movies_by_genre (genre, year, title) values ('Action|Crime|Thriller', 1998, 'Nick the Sting');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|War', 2009, 'Sharpe''s Eagle');
insert into movies_by_genre (genre, year, title) values ('Drama', 1987, 'Legend of Lizzie Borden, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 2006, 'Doctor at Large');
insert into movies_by_genre (genre, year, title) values ('Animation|Sci-Fi', 2012, 'Ultramarines: A Warhammer 40,000 Movie');
insert into movies_by_genre (genre, year, title) values ('Drama', 2008, 'Unbearable Lightness of Being, The');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2013, 'Kiss and Tell');
insert into movies_by_genre (genre, year, title) values ('Horror|Mystery|Thriller', 2003, '5 Dolls for an August Moon (5 bambole per la luna d''agosto)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 1994, 'No Strings Attached');
insert into movies_by_genre (genre, year, title) values ('Action|Comedy|Horror', 2002, 'Jack Brooks: Monster Slayer');
insert into movies_by_genre (genre, year, title) values ('Comedy|Fantasy|Romance', 2007, 'Midsummer Night''s Dream, A');
insert into movies_by_genre (genre, year, title) values ('Drama', 2010, 'Nobody Walks');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Thriller', 1997, 'Outrage');
insert into movies_by_genre (genre, year, title) values ('Comedy|Crime|Thriller', 2006, 'Lock, Stock & Two Smoking Barrels');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1993, 'I Feel Sleepy');
insert into movies_by_genre (genre, year, title) values ('Drama', 2005, 'Strip-tease');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Crime|Sci-Fi|Thriller', 2009, 'Black Mask (Hak hap)');
insert into movies_by_genre (genre, year, title) values ('Adventure|Drama|Romance', 1992, 'Camilla');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1988, 'Family United (La gran familia española)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 2007, 'Wonder Boys');
insert into movies_by_genre (genre, year, title) values ('Action|Crime|Drama', 2008, 'Hollywood Homicide');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1987, 'Scratch');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance|Sci-Fi', 2010, 'Miracle Mile');
insert into movies_by_genre (genre, year, title) values ('Action|Comedy', 1993, 'Big Bad Mama');
insert into movies_by_genre (genre, year, title) values ('Action|Comedy|Crime|Romance|Thriller', 1993, 'The Squeeze');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 1997, 'Bridge, The (Brücke, Die)');
insert into movies_by_genre (genre, year, title) values ('Drama', 1994, 'Cyberbully');
insert into movies_by_genre (genre, year, title) values ('Drama', 2005, 'Tree of Wooden Clogs, The (L''albero degli zoccoli)');
insert into movies_by_genre (genre, year, title) values ('Drama', 1996, 'Nobody Will Speak of Us When We''re Dead (Nadie hablará de nosotras cuando hayamos muerto)');
insert into movies_by_genre (genre, year, title) values ('Action|Drama|Thriller|IMAX', 2007, 'White House Down');
insert into movies_by_genre (genre, year, title) values ('Adventure|Children|Drama', 2006, 'Homeward Bound: The Incredible Journey');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 2012, '27 Dresses');
insert into movies_by_genre (genre, year, title) values ('Drama', 1992, 'Prozac Nation');
insert into movies_by_genre (genre, year, title) values ('Thriller', 2006, 'Blink');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1989, 'Free The Mind');
insert into movies_by_genre (genre, year, title) values ('Thriller', 1997, 'Mortician, The');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2004, 'Siblings');
insert into movies_by_genre (genre, year, title) values ('Western', 1995, 'Heaven''s Gate');
insert into movies_by_genre (genre, year, title) values ('Action|Sci-Fi|Thriller', 2010, 'Island, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Sci-Fi', 2006, 'Suburban Commando');
insert into movies_by_genre (genre, year, title) values ('Horror', 2008, 'Psychomania (Death Wheelers, The)');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Fantasy', 1994, 'Scorpion King, The');
insert into movies_by_genre (genre, year, title) values ('Drama', 1995, 'Nights and Weekends');
insert into movies_by_genre (genre, year, title) values ('Horror|Thriller', 2002, 'Hell''s Gate 11:11');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 2010, 'Finding Normal');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Thriller', 1987, 'Sitcom');
insert into movies_by_genre (genre, year, title) values ('Drama', 1997, 'Baadasssss! (How to Get the Man''s Foot Outta Your Ass)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 2000, 'Bulworth');
insert into movies_by_genre (genre, year, title) values ('Drama|Thriller', 2007, 'Poison Ivy: New Seduction');
insert into movies_by_genre (genre, year, title) values ('Drama', 1995, 'Human Capital (Il capitale umano)');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 1996, 'King & Country');
insert into movies_by_genre (genre, year, title) values ('Children|Drama', 1997, 'Black Beauty');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1986, 'Reality');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2000, 'Small Wonders');
insert into movies_by_genre (genre, year, title) values ('Drama|Sci-Fi', 1996, 'Enigma');
insert into movies_by_genre (genre, year, title) values ('War', 2000, 'Tumbledown');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Fantasy', 2010, 'Jason and the Argonauts');
insert into movies_by_genre (genre, year, title) values ('Action|Sci-Fi', 2012, 'Running Man, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 1997, '10');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1998, 'Debtocracy');
insert into movies_by_genre (genre, year, title) values ('Action|Drama|War', 1996, 'The Raid');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Comedy|Drama|War', 2006, 'Great War, The (Grande guerra, La)');
insert into movies_by_genre (genre, year, title) values ('Drama', 1996, 'Portrait of a Lady, The');
insert into movies_by_genre (genre, year, title) values ('Drama', 1992, 'The Princess of Egypt');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1999, 'No Flesh Shall Be Spared');
insert into movies_by_genre (genre, year, title) values ('Action|Musical|Romance', 2003, 'Disco Dancer');
insert into movies_by_genre (genre, year, title) values ('Action|Crime|Drama', 2010, 'Prime Cut');
insert into movies_by_genre (genre, year, title) values ('Mystery', 1999, 'Man from Beyond, The');
insert into movies_by_genre (genre, year, title) values ('Action|Crime|Drama|Thriller', 1993, 'History of Violence, A');
insert into movies_by_genre (genre, year, title) values ('Drama|Mystery|Thriller', 2007, 'Sleuth');
insert into movies_by_genre (genre, year, title) values ('Horror|Thriller', 2009, 'Session 9');
insert into movies_by_genre (genre, year, title) values ('Mystery', 2002, 'Charlie Chan''s Greatest Case');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Romance', 2002, 'Gravity (Schwerkraft)');
insert into movies_by_genre (genre, year, title) values ('Drama|Thriller', 2004, 'Confession, The (L''aveu)');
insert into movies_by_genre (genre, year, title) values ('Drama', 2002, 'Madison');
insert into movies_by_genre (genre, year, title) values ('Drama', 2005, 'Magic Hunter (Büvös vadász)');
insert into movies_by_genre (genre, year, title) values ('Drama', 1995, 'Man of My Life, The (L''homme de sa vie)');
insert into movies_by_genre (genre, year, title) values ('Action|Children|Comedy', 1984, '3 Ninjas');
insert into movies_by_genre (genre, year, title) values ('Horror|Sci-Fi', 2001, 'Teenagers from Outer Space');
insert into movies_by_genre (genre, year, title) values ('Horror|Thriller', 2005, 'Broken');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2002, 'National Lampoon''s Senior Trip');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2009, 'Stars in Shorts');
insert into movies_by_genre (genre, year, title) values ('Drama', 2001, 'High Cost of Living, The');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2002, 'First Love (Primo Amore)');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama', 1995, 'The Young Savages');
insert into movies_by_genre (genre, year, title) values ('Animation|Fantasy|Musical', 2000, 'Invitation to the Dance');
insert into movies_by_genre (genre, year, title) values ('Horror', 1996, 'Fall of the House of Usher, The (House of Usher)');
insert into movies_by_genre (genre, year, title) values ('Action|Crime|Drama', 2010, 'Fear Over the City');
insert into movies_by_genre (genre, year, title) values ('Action|Drama', 2004, 'Mr. Majestyk');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 2002, 'My Bollywood Bride');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2013, 'Wild Oranges');
insert into movies_by_genre (genre, year, title) values ('Action|Drama|Thriller', 2008, 'Marine, The');
insert into movies_by_genre (genre, year, title) values ('Drama', 2004, 'Triumph of the Spirit');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2002, 'The Suspended Step of the Stork');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1992, 'Lauderdale (a.k.a. Spring Break USA) (a.k.a. Spring Fever USA)');
insert into movies_by_genre (genre, year, title) values ('Action|Comedy|Crime|Thriller', 2005, 'Beverly Hills Cop II');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2010, 'National Lampoon''s Van Wilder');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 1989, 'Family Jewels, The (Eierdiebe)');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1992, 'Goya: Crazy Like a Genius');
insert into movies_by_genre (genre, year, title) values ('Drama', 2008, '11 Flowers (Wo 11)');
insert into movies_by_genre (genre, year, title) values ('Adventure|Children', 1993, 'Amazing Panda Adventure, The');
insert into movies_by_genre (genre, year, title) values ('Drama', 1992, 'Century');
insert into movies_by_genre (genre, year, title) values ('Musical|Romance', 1999, 'Carousel');
insert into movies_by_genre (genre, year, title) values ('Action|Crime', 2000, 'Dick Tracy');
insert into movies_by_genre (genre, year, title) values ('Animation|Comedy', 1959, 'Werner - Volles Rooäää');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance|War', 1996, 'Beyond Borders');
insert into movies_by_genre (genre, year, title) values ('Drama', 2003, 'Girl');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Thriller', 1997, 'Frailty');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2010, 'The Overnight');
insert into movies_by_genre (genre, year, title) values ('Drama|Fantasy|Mystery|Romance', 2007, 'Curious Case of Benjamin Button, The');
insert into movies_by_genre (genre, year, title) values ('Horror|Mystery|Thriller', 1997, 'Strange Behavior');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2000, 'Love Meetings (Comizi d''amore)');
insert into movies_by_genre (genre, year, title) values ('Drama', 1993, 'Stacy''s Knights');
insert into movies_by_genre (genre, year, title) values ('Drama', 2012, 'This is Martin Bonner');
insert into movies_by_genre (genre, year, title) values ('Drama', 2010, 'Home of the Brave');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Mystery|Thriller', 1996, 'Demonlover');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2012, 'Abendland');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2007, 'Quatre garçons pleins d''avenir');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1970, 'Attila Marcel');
insert into movies_by_genre (genre, year, title) values ('Drama', 1993, 'Dancing at Lughnasa');
insert into movies_by_genre (genre, year, title) values ('Adventure|Fantasy', 2009, 'Dinotopia');
insert into movies_by_genre (genre, year, title) values ('Action|Comedy', 2001, 'The Big Bus');
insert into movies_by_genre (genre, year, title) values ('Sci-Fi|Thriller', 2007, 'Limitless');
insert into movies_by_genre (genre, year, title) values ('Adventure|Children|Sci-Fi', 1996, 'Earth to Echo');
insert into movies_by_genre (genre, year, title) values ('Comedy|Musical', 2001, 'Artists and Models');
insert into movies_by_genre (genre, year, title) values ('Drama|Musical', 2005, 'You Got Served');
insert into movies_by_genre (genre, year, title) values ('Drama', 2007, 'Umberto D.');
insert into movies_by_genre (genre, year, title) values ('Comedy|Western', 2002, 'Ballad of Cable Hogue, The');
insert into movies_by_genre (genre, year, title) values ('(no genres listed)', 2010, 'Halloween');
insert into movies_by_genre (genre, year, title) values ('Thriller', 2011, 'Love Sick Love');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2011, 'God Said ''Ha!''');
insert into movies_by_genre (genre, year, title) values ('Romance', 1970, 'Love You You');
insert into movies_by_genre (genre, year, title) values ('Drama', 2011, 'Kitty');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2007, 'Punk''s Not Dead');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 2009, '$5 a Day');
insert into movies_by_genre (genre, year, title) values ('Action|Drama|Thriller', 1989, 'Unstoppable');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama', 2003, 'Pool Without Water, A (Mizu no nai puuru)');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|IMAX', 2011, 'Chinese Zodiac (Armour of God III) (CZ12)');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama', 2005, 'Parking (Ting che)');
insert into movies_by_genre (genre, year, title) values ('Drama', 1967, 'Aglaya');
insert into movies_by_genre (genre, year, title) values ('Drama', 2010, 'Tarda estate');
insert into movies_by_genre (genre, year, title) values ('Horror|Mystery|Thriller', 1997, 'Shutter');
insert into movies_by_genre (genre, year, title) values ('Adventure|Fantasy', 2009, 'Snowmageddon');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 2007, 'Finding North');
insert into movies_by_genre (genre, year, title) values ('Adventure|Children|Fantasy', 2006, 'Pelicanman (Pelikaanimies)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 1981, 'Day for Night (La Nuit Américaine)');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2009, 'Sea Gull, The');
insert into movies_by_genre (genre, year, title) values ('Drama', 1986, 'I Dreamed of Africa');
insert into movies_by_genre (genre, year, title) values ('Action|Comedy|Crime|Thriller', 1986, 'Ice Harvest, The');
insert into movies_by_genre (genre, year, title) values ('Drama|Western', 2010, 'Streets of Laredo');
insert into movies_by_genre (genre, year, title) values ('Drama', 1996, 'Wrong Move, The (Falsche Bewegung)');
insert into movies_by_genre (genre, year, title) values ('Drama|Sci-Fi', 1989, 'Forbidden Planet');
insert into movies_by_genre (genre, year, title) values ('Comedy|Sci-Fi', 1996, 'Tammy and the T-Rex');
insert into movies_by_genre (genre, year, title) values ('Comedy|Crime', 2010, 'Thin Man, The');
insert into movies_by_genre (genre, year, title) values ('(no genres listed)', 2011, 'Light Is Calling');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1993, 'Make Believe');
insert into movies_by_genre (genre, year, title) values ('Action', 2007, 'Magnificent Bodyguards (Fei du juan yun shan)');
insert into movies_by_genre (genre, year, title) values ('Drama', 2006, 'Air Doll (Kûki ningyô)');
insert into movies_by_genre (genre, year, title) values ('Children|Comedy', 1999, 'Harry and the Hendersons');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2002, 'Stricken (Er komt een vrouw bij de dokter)');
insert into movies_by_genre (genre, year, title) values ('Drama|Fantasy|Romance|Thriller', 2011, 'If Only');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 2001, 'Eichmann');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1990, 'Last Wedding, The (Kivenpyörittäjän kylä)');
insert into movies_by_genre (genre, year, title) values ('Drama|Horror|Sci-Fi', 1997, 'Flesh for Frankenstein (a.k.a. Andy Warhol''s Frankenstein)');
insert into movies_by_genre (genre, year, title) values ('Horror|Thriller', 1994, 'After Midnight');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2008, 'Farmer''s Wife, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 1999, 'Love Affair');
insert into movies_by_genre (genre, year, title) values ('Action|Children|Comedy', 1994, '3 Ninjas: High Noon On Mega Mountain');
insert into movies_by_genre (genre, year, title) values ('Horror', 1994, 'House III: The Horror Show');
insert into movies_by_genre (genre, year, title) values ('Drama', 2004, 'Dangerous Beauty');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1992, 'Bring It On');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1998, 'Saving Grace');
insert into movies_by_genre (genre, year, title) values ('Drama', 1991, 'Umberto D.');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1994, 'Regret to Inform');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2007, 'Father Hood');
insert into movies_by_genre (genre, year, title) values ('Children|Drama|War', 1990, 'Book Thief, The');
insert into movies_by_genre (genre, year, title) values ('Action', 2001, 'Wanted: Dead or Alive');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Romance', 2005, 'Kid Galahad');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Thriller', 2009, 'True Blue ');
insert into movies_by_genre (genre, year, title) values ('Adventure|Drama|Romance', 1994, 'Agora');
insert into movies_by_genre (genre, year, title) values ('Horror|Thriller', 1987, 'Devil''s Ground, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Horror|Sci-Fi', 2003, 'Doomsday Book');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 2002, 'Postman, The (Postino, Il)');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 1993, 'Way We Were, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Crime|Drama', 1990, 'Small Apartments');
insert into movies_by_genre (genre, year, title) values ('Comedy|Musical', 1999, 'Rovaniemen markkinoilla');
insert into movies_by_genre (genre, year, title) values ('Action|Comedy', 2011, 'They Call Him Bulldozer (Lo chiamavano Bulldozer)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 2004, 'She Hate Me');
insert into movies_by_genre (genre, year, title) values ('Drama', 2008, 'Innocence');
insert into movies_by_genre (genre, year, title) values ('Crime|Mystery|Sci-Fi|Thriller', 1999, 'S. Darko (S. Darko: A Donnie Darko Tale)');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2003, 'Confessions of a Driving Instructor');
insert into movies_by_genre (genre, year, title) values ('Animation', 1996, 'Merry Madagascar');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Film-Noir', 1993, 'Out of the Fog');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 2005, 'Kapò');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Crime|Drama|Thriller', 1984, 'City of God (Cidade de Deus)');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1986, 'Handle with Care (a.k.a. Citizen''s Band)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1995, 'Salut cousin!');
insert into movies_by_genre (genre, year, title) values ('Drama', 2007, 'Breath (Soom)');
insert into movies_by_genre (genre, year, title) values ('Action|Drama|Thriller', 2006, 'Zero Dark Thirty');
insert into movies_by_genre (genre, year, title) values ('Drama', 1991, 'Rough Riders');
insert into movies_by_genre (genre, year, title) values ('Mystery|Thriller', 1998, 'Shattered');
insert into movies_by_genre (genre, year, title) values ('Drama', 2001, 'Karate Kid, The');
insert into movies_by_genre (genre, year, title) values ('Drama', 1992, 'Foreverland');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 2003, 'Sideways');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama', 2004, 'Alpha Dog');
insert into movies_by_genre (genre, year, title) values ('(no genres listed)', 2012, 'Glumov''s Diary (Dnevnik Glumova)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Crime|Thriller', 1984, 'Lock, Stock & Two Smoking Barrels');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2011, 'Chump at Oxford, A');
insert into movies_by_genre (genre, year, title) values ('Comedy|Crime|Mystery', 2012, 'Mystery Team');
insert into movies_by_genre (genre, year, title) values ('Comedy|Musical|Romance', 1998, 'Boys & Girl from County Clare, The (a.k.a. The Boys from County Clare)');
insert into movies_by_genre (genre, year, title) values ('Action|Animation|Children|Comedy|IMAX', 2004, 'Kung Fu Panda');
insert into movies_by_genre (genre, year, title) values ('Action|Drama', 1999, 'Death Wish 5: The Face of Death');
insert into movies_by_genre (genre, year, title) values ('Drama|Thriller', 1997, 'Above Suspicion');
insert into movies_by_genre (genre, year, title) values ('Drama|Musical', 1995, 'Good Vibrations');
insert into movies_by_genre (genre, year, title) values ('Horror', 2006, 'Emergo (Apartment 143)');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 1975, 'Lonely Wife, The (Charulata)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 1999, 'French Twist (Gazon maudit)');
insert into movies_by_genre (genre, year, title) values ('Mystery|Thriller', 1993, 'Midnight Crossing');
insert into movies_by_genre (genre, year, title) values ('Adventure|Drama|Sci-Fi', 2002, 'Enemy Mine');
insert into movies_by_genre (genre, year, title) values ('Drama', 1994, 'Combat Girls (Kriegerin)');
insert into movies_by_genre (genre, year, title) values ('Drama', 2007, 'Bench, The (Bænken)');
insert into movies_by_genre (genre, year, title) values ('Adventure|Comedy|Drama|Fantasy|Romance', 2010, 'Click');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 1993, 'The Way He Looks');
insert into movies_by_genre (genre, year, title) values ('Drama', 1998, 'Mudlark, The');
insert into movies_by_genre (genre, year, title) values ('Action|Crime|Drama|Thriller', 1994, 'Crossing Guard, The');
insert into movies_by_genre (genre, year, title) values ('Drama', 1987, 'Escape Artist, The');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2003, 'Larger Than Life');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2008, 'Three Times (Zui hao de shi guang)');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1989, 'By the People: The Election of Barack Obama');
insert into movies_by_genre (genre, year, title) values ('Drama|Thriller', 1992, 'Serpent''s Egg, The (Schlangenei, Das)');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1989, 'National Gallery');
insert into movies_by_genre (genre, year, title) values ('Comedy|Crime|Drama', 2006, 'Amnèsia');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Film-Noir|Romance', 1995, 'Counterfeit Coin, The (Istoria mias kalpikis liras)');
insert into movies_by_genre (genre, year, title) values ('Western', 2005, 'Phantom Stagecoach, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 2009, 'Rewrite, The');
insert into movies_by_genre (genre, year, title) values ('Horror', 2013, 'Evil Dead');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1995, 'Imagine: John Lennon');
insert into movies_by_genre (genre, year, title) values ('Adventure|Thriller|War', 1997, 'Bravo Two Zero ');
insert into movies_by_genre (genre, year, title) values ('Drama', 2001, 'Stardust');
insert into movies_by_genre (genre, year, title) values ('Drama|Sci-Fi|Thriller', 1989, 'Snow Beast ');
insert into movies_by_genre (genre, year, title) values ('Thriller', 2006, 'Ipcress File, The');
insert into movies_by_genre (genre, year, title) values ('Horror|Thriller', 2004, 'Maniac');
insert into movies_by_genre (genre, year, title) values ('Comedy|Musical', 1995, 'Something in the Wind');
insert into movies_by_genre (genre, year, title) values ('Horror|Mystery|Thriller', 1995, '6 Souls (Shelter)');
insert into movies_by_genre (genre, year, title) values ('Action|Crime|Romance', 1997, 'Truth or Consequences, N.M.');
insert into movies_by_genre (genre, year, title) values ('Drama', 1994, 'On the Beach');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 1997, 'Theory of Flight, The');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Comedy|Crime', 2001, '99 and 44/100% Dead');
insert into movies_by_genre (genre, year, title) values ('Comedy|Fantasy|Romance', 1987, 'Sherlock Jr.');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 2006, 'Regeneration');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 1992, '36 fillette');
insert into movies_by_genre (genre, year, title) values ('Action|Comedy|Drama|Thriller', 1994, 'Into the Night');
insert into movies_by_genre (genre, year, title) values ('Comedy|Documentary', 2004, 'Who''s the Caboose?');
insert into movies_by_genre (genre, year, title) values ('Comedy|Sci-Fi', 1992, 'Amazon Women on the Moon');
insert into movies_by_genre (genre, year, title) values ('Romance|Thriller', 1992, 'Falling Awake');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2000, 'Houseguest');
insert into movies_by_genre (genre, year, title) values ('Documentary|Drama|Musical', 2006, '20,000 Days on Earth');
insert into movies_by_genre (genre, year, title) values ('Documentary|Musical|IMAX', 1969, 'All Access');
insert into movies_by_genre (genre, year, title) values ('Comedy|Horror|Musical', 2005, 'Little Shop of Horrors');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 1992, 'Boy in the Striped Pajamas, The (Boy in the Striped Pyjamas, The)');
insert into movies_by_genre (genre, year, title) values ('Horror', 2006, 'Pit and the Pendulum, The');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Mystery|Thriller', 2007, 'Black Coal, Thin Ice (Bai ri yan huo)');
insert into movies_by_genre (genre, year, title) values ('Horror|Thriller', 1994, 'Children of the Corn: Genesis');
insert into movies_by_genre (genre, year, title) values ('Comedy|Musical', 2007, 'Great Race, The');
insert into movies_by_genre (genre, year, title) values ('Action|Sci-Fi|IMAX', 1994, 'The Amazing Spider-Man 2');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1992, 'Mumia Abu-Jamal: A Case for Reasonable Doubt?');
insert into movies_by_genre (genre, year, title) values ('Comedy|Sci-Fi', 2010, 'Space Milkshake');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2012, 'Visioneers');
insert into movies_by_genre (genre, year, title) values ('Drama', 2012, 'Siddhartha');
insert into movies_by_genre (genre, year, title) values ('Drama|Musical', 1999, 'Zoot Suit');
insert into movies_by_genre (genre, year, title) values ('Thriller', 1999, 'No Place to Hide');
insert into movies_by_genre (genre, year, title) values ('Crime|Documentary', 1987, 'Tales of the Grim Sleeper');
insert into movies_by_genre (genre, year, title) values ('Drama', 2006, 'Dhobi Ghat');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance|Thriller', 2006, 'Aaron Loves Angela');
insert into movies_by_genre (genre, year, title) values ('Action|Drama|Romance', 1994, 'Ishaqzaade');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Thriller', 2000, 'Cleanskin');
insert into movies_by_genre (genre, year, title) values ('Drama', 2006, 'Caught');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1998, 'Marie-Jo and Her 2 Lovers (Marie-Jo et ses 2 amours)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Crime|Drama|Horror', 2002, 'Ex Drummer');
insert into movies_by_genre (genre, year, title) values ('Drama', 1990, 'Quiet Room, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance|Thriller', 2003, 'So I Married an Axe Murderer');
insert into movies_by_genre (genre, year, title) values ('Drama', 2009, 'Deficit (Déficit)');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Romance', 2012, 'Havoc');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Thriller', 2007, 'Debutantes, Los');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Drama|War', 1995, 'Von Ryan''s Express');
insert into movies_by_genre (genre, year, title) values ('Drama', 2008, 'Rocky');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2008, 'Cleopatra');
insert into movies_by_genre (genre, year, title) values ('Drama|Fantasy|Horror', 2011, 'Escape From Tomorrow');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2005, 'Stonewall Uprising');
insert into movies_by_genre (genre, year, title) values ('Drama', 2007, 'Broken Windows');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2001, 'Milky Way, The');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Comedy|Romance', 2012, 'Four Musketeers, The');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance|Thriller', 2001, 'Going to Kansas City');
insert into movies_by_genre (genre, year, title) values ('Drama', 2004, 'Geographer Drank His Globe Away, The (Geograf globus propil)');
insert into movies_by_genre (genre, year, title) values ('Adventure|Animation|Children|Comedy|Fantasy', 2001, 'Shrek the Third');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Drama|Romance', 1997, 'Temptation of a Monk (You Seng)');
insert into movies_by_genre (genre, year, title) values ('Drama', 1996, 'Cake Eaters, The');
insert into movies_by_genre (genre, year, title) values ('Adventure|Children|Drama', 1988, 'Kidnapped');
insert into movies_by_genre (genre, year, title) values ('Action|Comedy|Romance', 1991, 'Chinese Odyssey 2002 (Tian xia wu shuang)');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Drama|Romance|War', 1993, 'Yank in the R.A.F., A');
insert into movies_by_genre (genre, year, title) values ('Horror|Thriller', 2002, 'Venom');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1998, 'Middle of Nowhere');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2004, 'Friends with Kids');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 1997, 'Trial of Joan of Arc, The (Procès de Jeanne d''Arc)');
insert into movies_by_genre (genre, year, title) values ('Horror', 2002, 'House of Frankenstein');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 2006, 'Anatahan');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2002, 'Still Waiting...');
insert into movies_by_genre (genre, year, title) values ('Adventure|Animation|Children|Comedy', 2004, 'The Wind in the Willows');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1988, 'Roxie Hart');
insert into movies_by_genre (genre, year, title) values ('Adventure|Comedy|Crime|Drama|Romance', 1997, 'Beat the Devil');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2010, 'Captain Mike Across America (Slacker Uprising)');
insert into movies_by_genre (genre, year, title) values ('Drama|Fantasy|Romance', 1995, 'Wristcutters: A Love Story');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2002, 'Cool Runnings');
insert into movies_by_genre (genre, year, title) values ('Drama', 2006, 'Havana');
insert into movies_by_genre (genre, year, title) values ('Horror|Thriller', 1993, 'Cursed');
insert into movies_by_genre (genre, year, title) values ('Action|Drama|Thriller', 2004, 'Lone Wolf and Cub: Baby Cart in the Land of Demons (Kozure Ôkami: Meifumadô)');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2010, 'Carbon Nation');
insert into movies_by_genre (genre, year, title) values ('Animation|Children|Drama|Fantasy', 2004, 'My Neighbor Totoro (Tonari no Totoro)');
insert into movies_by_genre (genre, year, title) values ('Action|Sci-Fi', 2001, 'District 13: Ultimatum (Banlieue 13 - Ultimatum)');
insert into movies_by_genre (genre, year, title) values ('Adventure|Comedy', 1994, 'Money Money Money (L''aventure, c''est l''aventure)');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 1996, 'Private Fears in Public Places (Coeurs)');
insert into movies_by_genre (genre, year, title) values ('Action|Crime|Drama|Thriller', 2011, 'Colt 38 Special Squad');
insert into movies_by_genre (genre, year, title) values ('(no genres listed)', 1992, 'Password: Uccidete agente Gordon');
insert into movies_by_genre (genre, year, title) values ('Drama', 1990, 'Medea');
insert into movies_by_genre (genre, year, title) values ('Adventure|Children|Drama', 1992, 'Free Willy 2: The Adventure Home');
insert into movies_by_genre (genre, year, title) values ('Drama', 1993, 'Bamba, La');
insert into movies_by_genre (genre, year, title) values ('Action|Comedy|Romance', 2000, 'Grandma''s Boy');
insert into movies_by_genre (genre, year, title) values ('Documentary|Drama', 2003, 'Nostalgia for the Light (Nostalgia de la luz)');
insert into movies_by_genre (genre, year, title) values ('Action', 1987, 'Super Bitch');
insert into movies_by_genre (genre, year, title) values ('Sci-Fi', 2001, 'Zodiac');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 2007, 'Love in the Afternoon');
insert into movies_by_genre (genre, year, title) values ('Western', 1988, 'Far Horizons, The');
insert into movies_by_genre (genre, year, title) values ('Mystery', 2012, 'Five Angles on Murder');
insert into movies_by_genre (genre, year, title) values ('Action|Adventure|Drama|Thriller|War', 2009, 'Centurion');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 2006, 'Me Myself I');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 2002, 'Mr. 3000');
insert into movies_by_genre (genre, year, title) values ('Drama', 2008, 'Hard Way, The');
insert into movies_by_genre (genre, year, title) values ('Horror|Mystery|Thriller', 2012, 'Wicker Man, The');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2003, 'Four Seasons (Seasons, The) (Vremena goda)');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 1995, 'Love Without Pity');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1968, 'To Tulsa and Back: On Tour with J.J. Cale');
insert into movies_by_genre (genre, year, title) values ('Thriller', 1997, 'Blue Ruin');
insert into movies_by_genre (genre, year, title) values ('Action|Sci-Fi', 1991, 'Death Machine');
insert into movies_by_genre (genre, year, title) values ('Drama', 2009, 'Aliisa');
insert into movies_by_genre (genre, year, title) values ('Animation|Children|Musical', 2006, 'Cats Don''t Dance');
insert into movies_by_genre (genre, year, title) values ('Horror', 2000, 'Pyramid, The');
insert into movies_by_genre (genre, year, title) values ('Thriller', 2001, 'Odessa File, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Mystery|Romance', 2006, 'Star of Midnight');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 2010, 'Waiting to Exhale');
insert into movies_by_genre (genre, year, title) values ('Comedy|Horror', 2012, 'I Bought a Vampire Motorcycle');
insert into movies_by_genre (genre, year, title) values ('Comedy|Musical|Romance', 2004, 'Three Little Words');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1992, 'Spite Marriage');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 2004, 'Double Harness');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama', 1995, 'Linda Linda Linda');
insert into movies_by_genre (genre, year, title) values ('Drama', 1998, 'Heart of America');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 1987, 'Thousand Clouds of Peace, A (Mil nubes de paz cercan el cielo, amor, jamás acabarás de ser amor)');
insert into movies_by_genre (genre, year, title) values ('Western', 2000, 'Wrath of God, The');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2001, 'Polyester');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2003, 'Larger Than Life');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2001, 'Pinochet Case, The (Cas Pinochet, Le)');
insert into movies_by_genre (genre, year, title) values ('Drama', 1995, 'Two Women');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2011, 'Pray the Devil Back to Hell');
insert into movies_by_genre (genre, year, title) values ('Adventure|Children|Fantasy', 1992, 'Alice in Wonderland');
insert into movies_by_genre (genre, year, title) values ('Drama|Fantasy|Romance', 2007, 'Orlando');
insert into movies_by_genre (genre, year, title) values ('Documentary', 1987, 'Ingmar Bergman Makes a Movie (Ingmar Bergman gör en film)');
insert into movies_by_genre (genre, year, title) values ('Comedy', 1993, 'Silent Movie');
insert into movies_by_genre (genre, year, title) values ('Drama', 1981, '3 Backyards');
insert into movies_by_genre (genre, year, title) values ('Drama|Horror|Thriller', 2009, 'Massacre at Central High');
insert into movies_by_genre (genre, year, title) values ('Drama|Mystery|Romance', 1963, 'Dangerous Liaisons');
insert into movies_by_genre (genre, year, title) values ('Drama', 2002, 'Onion Field, The');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2011, 'Empire Falls');
insert into movies_by_genre (genre, year, title) values ('War', 2009, 'Operation Daybreak');
insert into movies_by_genre (genre, year, title) values ('Romance|Western', 2009, 'More Dead Than Alive');
insert into movies_by_genre (genre, year, title) values ('Drama', 2005, 'Tumbleweeds');
insert into movies_by_genre (genre, year, title) values ('Drama', 2001, 'House of Sand and Fog');
insert into movies_by_genre (genre, year, title) values ('Animation|Drama|Romance|Sci-Fi|War', 1988, 'Place Promised in Our Early Days, The (Kumo no mukô, yakusoku no basho)');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2006, 'Deep Blue');
insert into movies_by_genre (genre, year, title) values ('Sci-Fi', 1997, 'Lathe of Heaven, The');
insert into movies_by_genre (genre, year, title) values ('Comedy|Fantasy', 1995, 'Drop Dead Fred');
insert into movies_by_genre (genre, year, title) values ('Drama|Horror|Thriller', 2004, 'Godsend');
insert into movies_by_genre (genre, year, title) values ('Drama', 2006, 'Moon in the Gutter, The (La lune dans le caniveau)');
insert into movies_by_genre (genre, year, title) values ('Adventure', 1995, 'Blackbeard, the Pirate');
insert into movies_by_genre (genre, year, title) values ('Comedy', 2000, 'Soul Kitchen');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 1992, 'Gabriela');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 2010, 'Arsenal');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama', 2007, 'Ruby');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 2006, 'One Man''s Hero');
insert into movies_by_genre (genre, year, title) values ('Comedy|Crime|Mystery', 2001, 'Inspector Clouseau');
insert into movies_by_genre (genre, year, title) values ('Drama|Romance', 2010, 'Get Real');
insert into movies_by_genre (genre, year, title) values ('Drama', 1993, 'Straits of Love and Hate, The (Aien kyo)');
insert into movies_by_genre (genre, year, title) values ('Drama', 2006, 'Kidulthood');
insert into movies_by_genre (genre, year, title) values ('Action|Drama|War', 2004, 'Enemy Below, The');
insert into movies_by_genre (genre, year, title) values ('Fantasy|Horror', 2010, 'Nightbreed');
insert into movies_by_genre (genre, year, title) values ('Drama|Sci-Fi', 2007, 'Stranded');
insert into movies_by_genre (genre, year, title) values ('Drama|War', 2008, 'Kippur');
insert into movies_by_genre (genre, year, title) values ('Drama|Musical', 2009, 'Bird');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2007, 'Revolution Will Not Be Televised, The (a.k.a. Chavez: Inside the Coup)');
insert into movies_by_genre (genre, year, title) values ('Crime|Drama|Thriller', 2006, 'Mitä meistä tuli');
insert into movies_by_genre (genre, year, title) values ('Adventure|Documentary', 2006, 'Blindsight');
insert into movies_by_genre (genre, year, title) values ('Comedy|Romance', 2000, 'Outsourced');
insert into movies_by_genre (genre, year, title) values ('Drama', 2010, 'Batch ''81');
insert into movies_by_genre (genre, year, title) values ('Horror', 1992, 'House of Dracula');
insert into movies_by_genre (genre, year, title) values ('Action|Comedy', 2008, 'Cannibal Women in the Avocado Jungle of Death');
insert into movies_by_genre (genre, year, title) values ('Comedy|Drama|Romance', 2009, 'Dieta mediterránea');
insert into movies_by_genre (genre, year, title) values ('Action|Drama|Mystery', 1993, 'New Gladiators (I guerrieri dell''anno 2072)');
insert into movies_by_genre (genre, year, title) values ('Drama', 1989, 'Mrs. Parker and the Vicious Circle');
insert into movies_by_genre (genre, year, title) values ('Documentary', 2009, 'Berlin: Symphony of a Great City (Berlin: Die Sinfonie der Großstadt)');
APPLY BATCH;